blank_issues_enabled: false
contact_links:
 - name: Technical Questions
   url: https://github.com/libp2p/js-libp2p/discussions/new?category=q-a
   about: Please ask technical questions in the js-libp2p Github Discussions forum.
 - name: Community-wide libp2p Discussion
   url: https://discuss.libp2p.io
   about: Discussions and questions about the libp2p community.
