name: Examples
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master

  test-examples:
    name: Test example ${{ matrix.example.name }}
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        example:
          - name: js-libp2p-example-circuit-relay
            repo: https://github.com/libp2p/js-libp2p-example-circuit-relay.git
            deps: libp2p@$PWD/packages/libp2p,@libp2p/websockets@$PWD/packages/transport-websockets
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - run: npx xvfb-maybe npm run test:external -- ${{ matrix.example.repo }} --deps '${{ matrix.example.deps }}'
