name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  CACHE_DIRS: |
    ./interop/dist
    ./interop/node_modules
    ./doc/node_modules

jobs:

  transport-interop:
    runs-on: ${{ fromJSON(github.repository == 'libp2p/js-libp2p' && '["self-hosted", "linux", "x64", "4xlarge"]' || '"ubuntu-latest"') }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Build images
        run: (cd interop && make -j 4)
      - name: Save package-lock.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: package locks
          path: |
            package-lock.json
            interop/package-lock.json
      - uses: libp2p/test-plans/.github/actions/run-interop-ping-test@fix/debug-js-build
        with:
          test-filter: js-libp2p-head
          extra-versions: ${{ github.workspace }}/interop/node-version.json ${{ github.workspace }}/interop/chromium-version.json ${{ github.workspace }}/interop/firefox-version.json
          s3-cache-bucket: ${{ vars.S3_LIBP2P_BUILD_CACHE_BUCKET_NAME }}
          s3-access-key-id: ${{ vars.S3_LIBP2P_BUILD_CACHE_AWS_ACCESS_KEY_ID }}
          s3-secret-access-key: ${{ secrets.S3_LIBP2P_BUILD_CACHE_AWS_SECRET_ACCESS_KEY }}
          worker-count: 16
