name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
           npm install
           npm run build

  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - uses: actions/cache@v2
      id: cache
      env:
        CACHE_NAME: cache-node-modules
      with:
        path: |
          ~/.cache
          ~/.npm
          ./node_modules
          ./dist
        key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
    - name: Install Dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install
        npm run build
    - run: npx aegir lint
    - run: npx aegir dep-check
    - uses: ipfs/aegir/actions/bundle-size@master
      name: size
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

  test-node:
    needs: check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: [16]
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/cache@v2
        id: cache
        if: matrix.os != 'windows-latest'
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test:node -- --cov --bail
      - uses: codecov/codecov-action@v1
  test-chrome:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test:browser -- -t browser -t webworker --bail
  test-firefox:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test:browser -- -t browser -t webworker --bail -- --browser firefox
  test-ts:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test:ts
  test-interop:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - uses: actions/cache@v2
        id: cache
        env:
          CACHE_NAME: cache-node-modules
        with:
          path: |
            ~/.cache
            ~/.npm
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
          npm run build
      - run: npm run test:interop -- --bail -- --exit
