name: Generate Performance Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ${{ steps.find-workdir.outputs.WORK_DIR }}
        run: npm ci

      - name: Generate Report
        run: npm run test

      - uses: actions/upload-artifact@v3
        with:
          name: perf-output
          path: |
            ${{ steps.find-workdir.outputs.WORK_DIR }}/perfReport.md
